stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker-registry/testapp:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34459
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
notification: {}
