apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-demo
  name: openshift-demo
spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      targetPort: 8080
      protocol: TCP
  selector:
    app: openshift-demo
